services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Domain\AssessmentRepository:
        class: App\Domain\AssessmentRepository
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - 'App\Domain\Assessment'

    App\Domain\AssessmentService:
        arguments:
            - '@App\Domain\AssessmentRepository'
